# Generated by Django 5.0.6 on 2024-07-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0003_rename_cover_url_game_cover_url_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(related_name='users', through='core.UserGame', to='core.game'),
        ),
    ]
