# Generated by Django 5.0.6 on 2024-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_game_companies_engine_engine_name_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='cover_url',
            new_name='cover_url_high',
        ),
        migrations.AddField(
            model_name='game',
            name='cover_url_low',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
